title:              "D캔두"
tagline:            "하고싶은건 뭐든 할 수 있는 마케터D"
email:              "onlydcando@gmail.com"
description:        "하고싶은것은 어떻게든 노력해서 할 수 있게끔만드는 마케터D의 블로그"
author:             "마케터D"
baseurl:            ""
url:                "https://dcando.kr"
locale:             "ko_KR"
thumbnail:          "/img/main_thumbnail.png"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
highlighter: rouge

# 블로그 disqus shortname
disqus:
  shortname: dcando
